export default function Terms() {
  return (
    <main style={{
      maxWidth: '860px', margin: '0 auto', padding: '80px 24px',
      fontFamily: 'monospace', color: '#e0e0e0', background: '#0a0a0a', minHeight: '100vh'
    }}>
      <p style={{color: '#00bcd4', fontSize: '11px', letterSpacing: '4px', marginBottom: '8px'}}>LEGAL — SYS.01</p>
      <h1 style={{fontSize: '42px', fontWeight: 900, color: '#fff', marginBottom: '4px'}}>TERMS OF SERVICE</h1>
      <p style={{color: '#555', fontSize: '12px', marginBottom: '60px'}}>Effective date: May 7, 2026 — Vextar, Inc.</p>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>1. ACCEPTANCE OF TERMS</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>By accessing or using Vextar ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to all of these terms, you are not permitted to use the Service. These terms apply to all users, including visitors, registered users, and paying subscribers.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>2. DESCRIPTION OF SERVICE</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>Vextar is an AI-powered coding assistant delivered as a Software-as-a-Service (SaaS) product. The Service allows users to generate, refactor, analyze, and optimize code using artificial intelligence. Vextar leverages third-party AI models to process your requests. The Service is provided "as is" and may be updated, modified, or discontinued at any time.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>3. ACCOUNTS & REGISTRATION</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>You must create an account to use Vextar. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You agree to provide accurate, current, and complete information during registration. Vextar reserves the right to terminate accounts that contain false or misleading information.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>4. SUBSCRIPTIONS & PAYMENTS</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>Vextar offers paid subscription plans. All payments are processed securely through Paddle, our Merchant of Record. By subscribing, you authorize Paddle to charge your payment method on a recurring basis according to your selected plan. Prices are listed in USD and may be subject to local taxes depending on your jurisdiction, which Paddle handles automatically. You can cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>5. REFUND POLICY</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>Refund requests are evaluated on a case-by-case basis. If you believe you are entitled to a refund, contact us at support@vextar.org within 7 days of the charge. We do not offer refunds for partial subscription periods or for usage already consumed. All refund decisions are final.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>6. ACCEPTABLE USE</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>You agree not to use Vextar to: generate malicious code, malware, or exploits; violate any applicable laws or regulations; infringe on intellectual property rights of third parties; attempt to reverse engineer, scrape, or extract data from the Service; impersonate other users or entities; or transmit harmful, offensive, or illegal content. Vextar reserves the right to suspend or terminate access for any violation without notice.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>7. AI-GENERATED CONTENT</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>Code and content generated by Vextar is produced by AI and may not always be accurate, complete, or production-ready. You are solely responsible for reviewing, testing, and validating any output before using it in production environments. Vextar does not guarantee the correctness, security, or fitness for purpose of AI-generated output.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>8. INTELLECTUAL PROPERTY</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>The Vextar name, logo, interface, and underlying technology are the intellectual property of Vextar, Inc. You retain ownership of any code or content you input into the Service. Code generated by Vextar in response to your prompts is provided to you for your use, subject to any restrictions imposed by the underlying AI model provider.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>9. LIMITATION OF LIABILITY</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>To the maximum extent permitted by law, Vextar and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the Service. Our total liability to you for any claim shall not exceed the amount you paid to Vextar in the 3 months preceding the claim.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>10. DISCLAIMER OF WARRANTIES</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. Vextar does not warrant that the Service will be uninterrupted, error-free, or free of harmful components.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>11. GOVERNING LAW</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>These Terms are governed by and construed in accordance with applicable international commercial law. Any disputes shall be resolved through binding arbitration or in a court of competent jurisdiction, at Vextar's discretion.</p>
      </section>

      <section style={{marginBottom: '40px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>12. CHANGES TO TERMS</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>We reserve the right to update these Terms at any time. We will notify users of significant changes via email or an in-app notice. Continued use of the Service after changes take effect constitutes your acceptance of the revised Terms.</p>
      </section>

      <section style={{marginBottom: '60px'}}>
        <h2 style={{color: '#00bcd4', fontSize: '13px', letterSpacing: '3px'}}>13. CONTACT</h2>
        <p style={{lineHeight: '1.8', color: '#aaa'}}>For legal inquiries or questions about these Terms, contact us at: <a href="mailto:support@vextar.org" style={{color: '#00bcd4'}}>support@vextar.org</a></p>
      </section>

      <p style={{color: '#333', fontSize: '11px', borderTop: '1px solid #1a1a1a', paddingTop: '20px'}}>© 2026 Vextar, Inc. All rights reserved.</p>
    </main>
  );
}
